// <auto-generated />
namespace GrayBShop.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Grayy : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Grayy));
        
        string IMigrationMetadata.Id
        {
            get { return "202204201449403_Grayy"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
